version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: ${name}
    container_name: cinerex_db
    volumes:
      - ./postgres:/var/lib/postgresql/data


# Uncomment the following section to enable the backend service
# backend:
#     build: .
#     ports:
#       - '3000:3000'
#     container_name: cinerex_backend
#     depends_on:
#       - db
#     environment:
#       - SEED_ADMIN=true
#       - JWT_KEY=AJSIDU8WDE@KDJDIWEDJIDDS23DED
#       - NODE_ENV=development
#     volumes:
#       - .:/app
#     command: npm run start:dev